// <auto-generated />
namespace MvcApplication2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Change01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change01));
        
        string IMigrationMetadata.Id
        {
            get { return "201407242043085_Change 01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
